ALTER TABLE profile
    ADD COLUMN surname VARCHAR NOT NULL,
    ADD COLUMN email VARCHAR NOT NULL,
    ADD COLUMN birthdate VARCHAR NOT NULL,
    ADD COLUMN password VARCHAR NOT NULL;
ALTER TABLE profile DROP CONSTRAINT profile_pkey;
ALTER TABLE profile RENAME COLUMN id TO username;
ALTER TABLE profile ALTER COLUMN username TYPE VARCHAR;
ALTER TABLE profile ADD PRIMARY KEY (username);